/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/LeePerrySmith.glb --output src/components/canvas/AnatomyModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LeePerrySmith.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LeePerrySmith.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/LeePerrySmith.glb')
