/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/BrainStem.glb --output src/components/canvas/BrainStemModel.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/BrainStem.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group>
            <group rotation={[Math.PI / 2, -0.001, 0]}>
              <primitive object={nodes['']} />
            </group>
          </group>
          <group>
            <skinnedMesh name="Figure_2_geometry" geometry={nodes.Figure_2_geometry.geometry} material={materials['frameInStem-effect']} skeleton={nodes.Figure_2_geometry.skeleton} />
            <skinnedMesh name="Figure_2_geometry_1" geometry={nodes.Figure_2_geometry_1.geometry} material={materials['componentsStem-effect']} skeleton={nodes.Figure_2_geometry_1.skeleton} />
            <skinnedMesh name="Figure_2_geometry_2" geometry={nodes.Figure_2_geometry_2.geometry} material={materials['Stem-effect']} skeleton={nodes.Figure_2_geometry_2.skeleton} />
            <skinnedMesh name="Figure_2_geometry_3" geometry={nodes.Figure_2_geometry_3.geometry} material={materials['footStem-effect']} skeleton={nodes.Figure_2_geometry_3.skeleton} />
            <skinnedMesh name="Figure_2_geometry_4" geometry={nodes.Figure_2_geometry_4.geometry} material={materials['footFlangeStem-effect']} skeleton={nodes.Figure_2_geometry_4.skeleton} />
            <skinnedMesh name="Figure_2_geometry_5" geometry={nodes.Figure_2_geometry_5.geometry} material={materials['kneeStem-effect']} skeleton={nodes.Figure_2_geometry_5.skeleton} />
            <skinnedMesh name="Figure_2_geometry_6" geometry={nodes.Figure_2_geometry_6.geometry} material={materials['hipSphereStem-effect']} skeleton={nodes.Figure_2_geometry_6.skeleton} />
            <skinnedMesh name="Figure_2_geometry_7" geometry={nodes.Figure_2_geometry_7.geometry} material={materials['filletStem-effect']} skeleton={nodes.Figure_2_geometry_7.skeleton} />
            <skinnedMesh name="Figure_2_geometry_8" geometry={nodes.Figure_2_geometry_8.geometry} material={materials['thighStem-effect']} skeleton={nodes.Figure_2_geometry_8.skeleton} />
            <skinnedMesh name="Figure_2_geometry_9" geometry={nodes.Figure_2_geometry_9.geometry} material={materials['thighPadStem-effect']} skeleton={nodes.Figure_2_geometry_9.skeleton} />
            <skinnedMesh name="Figure_2_geometry_10" geometry={nodes.Figure_2_geometry_10.geometry} material={materials['plugStem-effect']} skeleton={nodes.Figure_2_geometry_10.skeleton} />
            <skinnedMesh name="Figure_2_geometry_11" geometry={nodes.Figure_2_geometry_11.geometry} material={materials['discInStem-effect']} skeleton={nodes.Figure_2_geometry_11.skeleton} />
            <skinnedMesh name="Figure_2_geometry_12" geometry={nodes.Figure_2_geometry_12.geometry} material={materials['TubeStem-effect']} skeleton={nodes.Figure_2_geometry_12.skeleton} />
            <skinnedMesh name="Figure_2_geometry_13" geometry={nodes.Figure_2_geometry_13.geometry} material={materials['componentStem-effect']} skeleton={nodes.Figure_2_geometry_13.skeleton} />
            <skinnedMesh name="Figure_2_geometry_14" geometry={nodes.Figure_2_geometry_14.geometry} material={materials['hexStem-effect']} skeleton={nodes.Figure_2_geometry_14.skeleton} />
            <skinnedMesh name="Figure_2_geometry_15" geometry={nodes.Figure_2_geometry_15.geometry} material={materials['kneeGuardStem-effect']} skeleton={nodes.Figure_2_geometry_15.skeleton} />
            <skinnedMesh name="Figure_2_geometry_16" geometry={nodes.Figure_2_geometry_16.geometry} material={materials['calfStem-effect']} skeleton={nodes.Figure_2_geometry_16.skeleton} />
            <skinnedMesh name="Figure_2_geometry_17" geometry={nodes.Figure_2_geometry_17.geometry} material={materials['ankleBracketStem-effect']} skeleton={nodes.Figure_2_geometry_17.skeleton} />
            <skinnedMesh name="Figure_2_geometry_18" geometry={nodes.Figure_2_geometry_18.geometry} material={materials['ankleStem-effect']} skeleton={nodes.Figure_2_geometry_18.skeleton} />
            <skinnedMesh name="Figure_2_geometry_19" geometry={nodes.Figure_2_geometry_19.geometry} material={materials['calfCoverStem-effect']} skeleton={nodes.Figure_2_geometry_19.skeleton} />
            <skinnedMesh name="Figure_2_geometry_20" geometry={nodes.Figure_2_geometry_20.geometry} material={materials['knee2Stem-effect']} skeleton={nodes.Figure_2_geometry_20.skeleton} />
            <skinnedMesh name="Figure_2_geometry_21" geometry={nodes.Figure_2_geometry_21.geometry} material={materials['skeletonStem-effect']} skeleton={nodes.Figure_2_geometry_21.skeleton} />
            <skinnedMesh name="Figure_2_geometry_22" geometry={nodes.Figure_2_geometry_22.geometry} material={materials['bracketStem-effect']} skeleton={nodes.Figure_2_geometry_22.skeleton} />
            <skinnedMesh name="Figure_2_geometry_23" geometry={nodes.Figure_2_geometry_23.geometry} material={materials['coverStem-effect']} skeleton={nodes.Figure_2_geometry_23.skeleton} />
            <skinnedMesh name="Figure_2_geometry_24" geometry={nodes.Figure_2_geometry_24.geometry} material={materials['barStem-effect']} skeleton={nodes.Figure_2_geometry_24.skeleton} />
            <skinnedMesh name="Figure_2_geometry_25" geometry={nodes.Figure_2_geometry_25.geometry} material={materials['intestineOutStem-effect']} skeleton={nodes.Figure_2_geometry_25.skeleton} />
            <skinnedMesh name="Figure_2_geometry_26" geometry={nodes.Figure_2_geometry_26.geometry} material={materials['neckSinkStem-effect']} skeleton={nodes.Figure_2_geometry_26.skeleton} />
            <skinnedMesh name="Figure_2_geometry_27" geometry={nodes.Figure_2_geometry_27.geometry} material={materials['shockOutStem-effect']} skeleton={nodes.Figure_2_geometry_27.skeleton} />
            <skinnedMesh name="Figure_2_geometry_28" geometry={nodes.Figure_2_geometry_28.geometry} material={materials['shockInStem-effect']} skeleton={nodes.Figure_2_geometry_28.skeleton} />
            <skinnedMesh name="Figure_2_geometry_29" geometry={nodes.Figure_2_geometry_29.geometry} material={materials['discStem-effect']} skeleton={nodes.Figure_2_geometry_29.skeleton} />
            <skinnedMesh name="Figure_2_geometry_30" geometry={nodes.Figure_2_geometry_30.geometry} material={materials['canisterInStem-effect']} skeleton={nodes.Figure_2_geometry_30.skeleton} />
            <skinnedMesh name="Figure_2_geometry_31" geometry={nodes.Figure_2_geometry_31.geometry} material={materials['canisterOutStem-effect']} skeleton={nodes.Figure_2_geometry_31.skeleton} />
            <skinnedMesh name="Figure_2_geometry_32" geometry={nodes.Figure_2_geometry_32.geometry} material={materials['canInnerStem-effect']} skeleton={nodes.Figure_2_geometry_32.skeleton} />
            <skinnedMesh name="Figure_2_geometry_33" geometry={nodes.Figure_2_geometry_33.geometry} material={materials['pipeStem-effect']} skeleton={nodes.Figure_2_geometry_33.skeleton} />
            <skinnedMesh name="Figure_2_geometry_34" geometry={nodes.Figure_2_geometry_34.geometry} material={materials['off-effect']} skeleton={nodes.Figure_2_geometry_34.skeleton} />
            <skinnedMesh name="Figure_2_geometry_35" geometry={nodes.Figure_2_geometry_35.geometry} material={materials['boltStem-effect']} skeleton={nodes.Figure_2_geometry_35.skeleton} />
            <skinnedMesh name="Figure_2_geometry_36" geometry={nodes.Figure_2_geometry_36.geometry} material={materials['intestineInStem-effect']} skeleton={nodes.Figure_2_geometry_36.skeleton} />
            <skinnedMesh name="Figure_2_geometry_37" geometry={nodes.Figure_2_geometry_37.geometry} material={materials['armPlateStem-effect']} skeleton={nodes.Figure_2_geometry_37.skeleton} />
            <skinnedMesh name="Figure_2_geometry_38" geometry={nodes.Figure_2_geometry_38.geometry} material={materials['shoulderPodStem-effect']} skeleton={nodes.Figure_2_geometry_38.skeleton} />
            <skinnedMesh name="Figure_2_geometry_39" geometry={nodes.Figure_2_geometry_39.geometry} material={materials['armFilletStem-effect']} skeleton={nodes.Figure_2_geometry_39.skeleton} />
            <skinnedMesh name="Figure_2_geometry_40" geometry={nodes.Figure_2_geometry_40.geometry} material={materials['bStem-effect']} skeleton={nodes.Figure_2_geometry_40.skeleton} />
            <skinnedMesh name="Figure_2_geometry_41" geometry={nodes.Figure_2_geometry_41.geometry} material={materials['armBoltStem-effect']} skeleton={nodes.Figure_2_geometry_41.skeleton} />
            <skinnedMesh name="Figure_2_geometry_42" geometry={nodes.Figure_2_geometry_42.geometry} material={materials['shoulderBStem-effect']} skeleton={nodes.Figure_2_geometry_42.skeleton} />
            <skinnedMesh name="Figure_2_geometry_43" geometry={nodes.Figure_2_geometry_43.geometry} material={materials['armTrussStem-effect']} skeleton={nodes.Figure_2_geometry_43.skeleton} />
            <skinnedMesh name="Figure_2_geometry_44" geometry={nodes.Figure_2_geometry_44.geometry} material={materials['pinStem-effect']} skeleton={nodes.Figure_2_geometry_44.skeleton} />
            <skinnedMesh name="Figure_2_geometry_45" geometry={nodes.Figure_2_geometry_45.geometry} material={materials['radiatorStem-effect']} skeleton={nodes.Figure_2_geometry_45.skeleton} />
            <skinnedMesh name="Figure_2_geometry_46" geometry={nodes.Figure_2_geometry_46.geometry} material={materials['rpgStem-effect']} skeleton={nodes.Figure_2_geometry_46.skeleton} />
            <skinnedMesh name="Figure_2_geometry_47" geometry={nodes.Figure_2_geometry_47.geometry} material={materials['bayonetStem-effect']} skeleton={nodes.Figure_2_geometry_47.skeleton} />
            <skinnedMesh name="Figure_2_geometry_48" geometry={nodes.Figure_2_geometry_48.geometry} material={materials['barrel2Stem-effect']} skeleton={nodes.Figure_2_geometry_48.skeleton} />
            <skinnedMesh name="Figure_2_geometry_49" geometry={nodes.Figure_2_geometry_49.geometry} material={materials['barrel1Stem-effect']} skeleton={nodes.Figure_2_geometry_49.skeleton} />
            <skinnedMesh name="Figure_2_geometry_50" geometry={nodes.Figure_2_geometry_50.geometry} material={materials['filterOutStem-effect']} skeleton={nodes.Figure_2_geometry_50.skeleton} />
            <skinnedMesh name="Figure_2_geometry_51" geometry={nodes.Figure_2_geometry_51.geometry} material={materials['filterInStem-effect']} skeleton={nodes.Figure_2_geometry_51.skeleton} />
            <skinnedMesh name="Figure_2_geometry_52" geometry={nodes.Figure_2_geometry_52.geometry} material={materials['exhaustGunStem-effect']} skeleton={nodes.Figure_2_geometry_52.skeleton} />
            <skinnedMesh name="Figure_2_geometry_53" geometry={nodes.Figure_2_geometry_53.geometry} material={materials['headFilletStem-effect']} skeleton={nodes.Figure_2_geometry_53.skeleton} />
            <skinnedMesh name="Figure_2_geometry_54" geometry={nodes.Figure_2_geometry_54.geometry} material={materials['headCaseStem-effect']} skeleton={nodes.Figure_2_geometry_54.skeleton} />
            <skinnedMesh name="Figure_2_geometry_55" geometry={nodes.Figure_2_geometry_55.geometry} material={materials['headGrillStem-effect']} skeleton={nodes.Figure_2_geometry_55.skeleton} />
            <skinnedMesh name="Figure_2_geometry_56" geometry={nodes.Figure_2_geometry_56.geometry} material={materials['headHornStem-effect']} skeleton={nodes.Figure_2_geometry_56.skeleton} />
            <skinnedMesh name="Figure_2_geometry_57" geometry={nodes.Figure_2_geometry_57.geometry} material={materials['eyeStem-effect']} skeleton={nodes.Figure_2_geometry_57.skeleton} />
            <skinnedMesh name="Figure_2_geometry_58" geometry={nodes.Figure_2_geometry_58.geometry} material={materials['eyeRimStem-effect']} skeleton={nodes.Figure_2_geometry_58.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/BrainStem.glb')
